version: "3.0"
services:
  app-apache:
    build: ./core
    ports:
      - "8080:8080"
    volumes:
      - ../core/code:/var/www/html
    depends_on:
      - app-mysql

  app-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    ports:
      - "3306"
    volumes:
      - "./core/.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: banco
      MYSQL_ROOT_PASSWORD: secret
